services:
  testDB:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs: /var/lib/postgresql
    ports:
      - 5432:5432

  backend:
    env_file:
      - ./tests/.env
    build: backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
    environment:
      - DB_HOST=testDB
    healthcheck:
      test: "curl --fail --request GET -H 'content-type:application/json' --url 'http://localhost:4001/graphql?query=%7B__typename%7D'"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      testDB:
        condition: service_healthy

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
