import Head from "next/head";
import Header from "../components/Header";
import { ReactNode, useState } from "react";

// Helpers
import { ads } from '@/helpers/ads';

// Interfaces
import { Ad } from "@/interfaces/ads";

interface LayoutProps {
    children: ReactNode;
    onSearch?: (query: string) => void;
}

export default function Layout({ children, onSearch }: LayoutProps) {
    return (
        <>
            <Head>
                <title>The Good Corner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header onSearch={onSearch} />
            <main className="main-content">{children}</main>
        </>
    )
};
