GET http://localhost:3000/tags
###
GET http://localhost:3000/tags/1
###
POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "tag3"
}
###
PATCH http://localhost:3000/tags/1
Content-Type: application/json

{
    "name": "tag1"
}
###
DELETE http://localhost:3000/tags/2
###